name: Deploy job notifier

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Setup Terraform state bucket
        run: |
          aws s3api create-bucket my-fancy-job-terraform-45678 --region eu-central-1 --create-bucket-configuration LocationConstraint=eu-central-1
      - name: Deploy with Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: eu-central-1
        run: |
          cd infrastructure
          terraform init
          terraform apply -auto-approve
